package diklat

import "time"

type Diklat struct {
	IDDiklat       string     `json:"id_diklat"`
	JenisDiklat    string     `json:"jenis_diklat"`
	Kategori       string     `json:"kategori"`
	BidangKeilmuan *string    `json:"bidang_keilmuan"`
	NamaDiklat     string     `json:"nama_diklat"`
	Penyelenggara  string     `json:"penyelenggara"`
	Tahun          string     `json:"tahun"`
	Peran          string     `json:"peran"`
	Durasi         string     `json:"durasi"`
	NoSert         *string    `json:"no_sert"`
	TglSert        *time.Time `json:"tgl_sert"`
	Tempat         string     `json:"tempat"`
	TglMulai       time.Time  `json:"tgl_mulai"`
	TglSelesai     time.Time  `json:"tgl_selesai"`
	SkTugas        *string    `json:"sk_tugas"`
	CreateDate     time.Time  `db:"create_date" json:"-"`
	LastUpdate     time.Time  `db:"last_update" json:"-"`
	ExpiredDate    *time.Time `db:"expired_date" json:"-"`
}

type DiklatCreateRequest struct {
	IDDiklat      string  `json:"id_diklat,omitempty"` // Will be generated by service if empty
	IDSDM         string  `json:"id_sdm" validate:"required"`
	IDKelBidang   *string `json:"id_kel_bidang"`
	IDKatGiat     string  `json:"id_katgiat" validate:"required"`
	IDJnsDiklat   string  `json:"id_jns_diklat" validate:"required"`
	NamaDiklat    string  `json:"nm_diklat" validate:"required"`
	Penyelenggara string  `json:"penyelenggara" validate:"required"`
	Tahun         string  `json:"thn" validate:"required"`
	Peran         string  `json:"peran" validate:"required"`
	Tingkat       string  `json:"tkt" validate:"required"`
	JumlahJam     string  `json:"jml_jam" validate:"required"`
	NoSertifikat  string  `json:"no_sert"`
	TglSert       string  `json:"tgl_sert"`
	Tempat        string  `json:"tempat" validate:"required"`
	TglMulai      string  `json:"tgl_mulai" validate:"required"`
	TglSelesai    string  `json:"tgl_selesai" validate:"required"`
	SkTugas       string  `json:"sk_tugas"`
	TglSkTugas    string  `json:"tgl_sk_tugas"`
}

type DiklatUpdateRequest struct {
	IDDiklat      string  `json:"id_diklat"`
	IDSDM         string  `json:"id_sdm"`
	IDKelBidang   *string `json:"id_kel_bidang"`
	IDKatGiat     string  `json:"id_katgiat"`
	IDJnsDiklat   string  `json:"id_jns_diklat"`
	NamaDiklat    string  `json:"nm_diklat"`
	Penyelenggara string  `json:"penyelenggara"`
	Tahun         string  `json:"thn"`
	Peran         string  `json:"peran"`
	Tingkat       string  `json:"tkt"`
	JumlahJam     string  `json:"jml_jam"`
	NoSertifikat  string  `json:"no_sert"`
	TglSert       string  `json:"tgl_sert"`
	Tempat        string  `json:"tempat"`
	TglMulai      string  `json:"tgl_mulai"`
	TglSelesai    string  `json:"tgl_selesai"`
	SkTugas       string  `json:"sk_tugas"`
	TglSkTugas    string  `json:"tgl_sk_tugas"`
}

type DiklatResponse struct {
	Status   bool             `json:"status"`
	Message  string           `json:"message"`
	Latency  float64          `json:"latency"`
	Data     interface{}      `json:"data,omitempty"`
	Error    *ValidationError `json:"error,omitempty"`
	Response interface{}      `json:"response,omitempty"`
}

type ValidationError map[string][]string

type DiklatParams struct {
	PaginationParams
	TglMulai *time.Time `query:"tgl_mulai"`
	Tahun    *string    `query:"tahun"`
}

// PaginationParams untuk parameter pagination standar
type PaginationParams struct {
	Page   int    `query:"page"`
	Limit  int    `query:"limit"`
	Search string `query:"search"`
	SortBy string `query:"sort_by"`
	Order  string `query:"order"` // asc atau desc
}

// ============================================================================
// Default Values
// ============================================================================

const (
	DefaultPage  = 1
	DefaultLimit = 20
	MaxLimit     = 100
)

// NormalizePagination memastikan nilai pagination valid
func (p *PaginationParams) NormalizePagination() {
	if p.Page < 1 {
		p.Page = DefaultPage
	}
	if p.Limit < 1 {
		p.Limit = DefaultLimit
	}
	if p.Limit > MaxLimit {
		p.Limit = MaxLimit
	}
	if p.Order != "asc" && p.Order != "desc" {
		p.Order = "asc"
	}
}

// Offset menghitung offset untuk query
func (p *PaginationParams) Offset() int {
	return (p.Page - 1) * p.Limit
}
