server {
    listen 8090;
    server_name localhost;

    location /stub_status {
        stub_status;
        allow 172.20.0.0/16;       # docker bridge default
        allow 172.20.1.0/24;       # docker bridge vm5
        allow 192.168.120.0/23;    # internal network
        allow 127.0.0.1;
        deny all;
    }
}
