services:
  apps:
    container_name: apps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    mem_limit: 512m
    cpus: 1.0
    

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network
    volumes:
      - redis-data:/data
    mem_limit: 256m
    cpus: 0.5

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local

