services:
  apps:
    container_name: apps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
