-- ============================================================
-- monitoring_15_seed_sites.sql
-- Seed data: Domain Unila dari https://bimasakti.unila.ac.id/DNS/
-- Crawled: 2026-03-02 | 249 dari 1168+ domain terdaftar
-- Jalankan crawl job untuk import domain sisanya secara otomatis
-- ============================================================
-- status: 'active' = site merespons (200/302/403/404)
--         'inactive' = site tidak merespons (0/500/502/503)
-- is_active = 1 untuk semua (tetap dimonitor)
-- ============================================================

MERGE monitoring.sites AS T
USING (VALUES
-- === FP (Fakultas Pertanian) ===
    (N'https://abe.fp.unila.ac.id',                        N'ABE (FP)',                        N'custom', N'active',   1, N'fp'),
    (N'https://agb.fp.unila.ac.id',                        N'AGB (FP)',                        N'custom', N'active',   1, N'fp'),
    (N'https://agh.fp.unila.ac.id',                        N'AGH (FP)',                        N'custom', N'active',   1, N'fp'),
    (N'https://agrohorti.fp.unila.ac.id',                  N'Agrohorti (FP)',                  N'custom', N'inactive', 1, N'fp'),
    (N'https://agroteknologi.fp.unila.ac.id',              N'Agroteknologi (FP)',              N'custom', N'active',   1, N'fp'),
    (N'https://bubalusjpm.fp.unila.ac.id',                 N'Bubalusjpm (FP)',                 N'custom', N'active',   1, N'fp'),
    (N'https://d3kebun.fp.unila.ac.id',                    N'D3 Kebun (FP)',                   N'custom', N'inactive', 1, N'fp'),
    (N'https://bem.fp.unila.ac.id',                        N'BEM (FP)',                        N'custom', N'inactive', 1, N'fp'),
-- === FEB (Fakultas Ekonomi dan Bisnis) ===
    (N'https://akademik.feb.unila.ac.id',                  N'Akademik (FEB)',                  N'custom', N'inactive', 1, N'feb'),
    (N'https://akd.feb.unila.ac.id',                       N'AKD (FEB)',                       N'custom', N'inactive', 1, N'feb'),
    (N'https://akuntansi.feb.unila.ac.id',                 N'Akuntansi (FEB)',                 N'custom', N'active',   1, N'feb'),
    (N'https://alumni.feb.unila.ac.id',                    N'Alumni (FEB)',                    N'custom', N'inactive', 1, N'feb'),
    (N'https://arsip.feb.unila.ac.id',                     N'Arsip (FEB)',                     N'custom', N'inactive', 1, N'feb'),
    (N'https://begawi.feb.unila.ac.id',                    N'Begawi (FEB)',                    N'custom', N'active',   1, N'feb'),
    (N'https://bisnisdigital.feb.unila.ac.id',             N'Bisnis Digital (FEB)',             N'custom', N'active',   1, N'feb'),
    (N'https://bmn.feb.unila.ac.id',                       N'BMN (FEB)',                       N'custom', N'inactive', 1, N'feb'),
    (N'https://d3-akuntansi.feb.unila.ac.id',              N'D3 Akuntansi (FEB)',              N'custom', N'inactive', 1, N'feb'),
    (N'https://d3-keuangan.feb.unila.ac.id',               N'D3 Keuangan (FEB)',               N'custom', N'inactive', 1, N'feb'),
    (N'https://d3-pajak.feb.unila.ac.id',                  N'D3 Pajak (FEB)',                  N'custom', N'inactive', 1, N'feb'),
    (N'https://d3-pemasaran.feb.unila.ac.id',              N'D3 Pemasaran (FEB)',              N'custom', N'inactive', 1, N'feb'),
    (N'https://d3akuntansi.feb.unila.ac.id',               N'D3 Akuntansi Alt (FEB)',          N'custom', N'inactive', 1, N'feb'),
    (N'https://d3keuangan.feb.unila.ac.id',                N'D3 Keuangan Alt (FEB)',           N'custom', N'inactive', 1, N'feb'),
    (N'https://d3pajak.feb.unila.ac.id',                   N'D3 Pajak Alt (FEB)',              N'custom', N'inactive', 1, N'feb'),
    (N'https://d3pemasaran.feb.unila.ac.id',               N'D3 Pemasaran Alt (FEB)',          N'custom', N'active',   1, N'feb'),
    (N'https://doktoral.feb.unila.ac.id',                  N'Doktoral (FEB)',                  N'custom', N'active',   1, N'feb'),
    (N'https://efebe.feb.unila.ac.id',                     N'EFEBE (FEB)',                     N'custom', N'active',   1, N'feb'),
-- === FISIP (Ilmu Sosial dan Ilmu Politik) ===
    (N'https://admbisnis.fisip.unila.ac.id',               N'Adm Bisnis (FISIP)',              N'custom', N'active',   1, N'fisip'),
    (N'https://administrasiperkantoran.fisip.unila.ac.id', N'Administrasi Perkantoran (FISIP)', N'custom', N'active',  1, N'fisip'),
    (N'https://administrativa.fisip.unila.ac.id',          N'Administrativa (FISIP)',          N'custom', N'active',   1, N'fisip'),
    (N'https://admnegara.fisip.unila.ac.id',               N'Adm Negara (FISIP)',              N'custom', N'active',   1, N'fisip'),
    (N'https://admperkantoran.fisip.unila.ac.id',          N'Adm Perkantoran (FISIP)',         N'custom', N'inactive', 1, N'fisip'),
    (N'https://akademik.fisip.unila.ac.id',                N'Akademik (FISIP)',                N'custom', N'inactive', 1, N'fisip'),
    (N'https://akplaboratory.fisip.unila.ac.id',           N'AKP Lab (FISIP)',                 N'custom', N'inactive', 1, N'fisip'),
    (N'https://anjungan.fisip.unila.ac.id',                N'Anjungan (FISIP)',                N'custom', N'inactive', 1, N'fisip'),
    (N'https://apps.fisip.unila.ac.id',                    N'Apps (FISIP)',                    N'custom', N'inactive', 1, N'fisip'),
    (N'https://bmn.fisip.unila.ac.id',                     N'BMN (FISIP)',                     N'custom', N'inactive', 1, N'fisip'),
    (N'https://Busme.admbisnis.fisip.unila.ac.id',         N'Busme Adm Bisnis (FISIP)',        N'custom', N'inactive', 1, N'fisip'),
    (N'https://cakrawala.fisip.unila.ac.id',               N'Cakrawala (FISIP)',               N'custom', N'inactive', 1, N'fisip'),
    (N'https://cendekia.fisip.unila.ac.id',                N'Cendekia (FISIP)',                N'custom', N'inactive', 1, N'fisip'),
-- === FK (Kedokteran) ===
    (N'https://aipt.fk.unila.ac.id',                       N'AIPT (FK)',                       N'custom', N'inactive', 1, N'fk'),
    (N'https://akademik.fk.unila.ac.id',                   N'Akademik (FK)',                   N'custom', N'inactive', 1, N'fk'),
    (N'https://anjungan.fk.unila.ac.id',                   N'Anjungan (FK)',                   N'custom', N'inactive', 1, N'fk'),
    (N'https://beasiswa.fk.unila.ac.id',                   N'Beasiswa (FK)',                   N'custom', N'inactive', 1, N'fk'),
    (N'https://bem.fk.unila.ac.id',                        N'BEM (FK)',                        N'custom', N'inactive', 1, N'fk'),
    (N'https://cbt.fk.unila.ac.id',                        N'CBT (FK)',                        N'custom', N'inactive', 1, N'fk'),
    (N'https://cimsa.fk.unila.ac.id',                      N'CIMSA (FK)',                      N'custom', N'inactive', 1, N'fk'),
    (N'https://dentist.fk.unila.ac.id',                    N'Dentist (FK)',                    N'custom', N'inactive', 1, N'fk'),
    (N'https://dies.fk.unila.ac.id',                       N'Dies (FK)',                       N'custom', N'inactive', 1, N'fk'),
    (N'https://digilib.fk.unila.ac.id',                    N'Digilib (FK)',                    N'custom', N'inactive', 1, N'fk'),
    (N'https://dosen.fk.unila.ac.id',                      N'Dosen (FK)',                      N'custom', N'inactive', 1, N'fk'),
-- === FKIP (Keguruan dan Ilmu Pendidikan) ===
    (N'https://akademik.fkip.unila.ac.id',                 N'Akademik (FKIP)',                 N'custom', N'active',   1, N'fkip'),
    (N'https://aksara.fkip.unila.ac.id',                   N'Aksara (FKIP)',                   N'custom', N'active',   1, N'fkip'),
    (N'https://arsip.fkip.unila.ac.id',                    N'Arsip (FKIP)',                    N'custom', N'inactive', 1, N'fkip'),
    (N'https://base.fkip.unila.ac.id',                     N'Base (FKIP)',                     N'custom', N'inactive', 1, N'fkip'),
    (N'https://beasiswa.fkip.unila.ac.id',                 N'Beasiswa (FKIP)',                 N'custom', N'inactive', 1, N'fkip'),
    (N'https://bem.fkip.unila.ac.id',                      N'BEM (FKIP)',                      N'custom', N'inactive', 1, N'fkip'),
    (N'https://biologi.fkip.unila.ac.id',                  N'Biologi (FKIP)',                  N'custom', N'active',   1, N'fkip'),
    (N'https://bind.fkip.unila.ac.id',                     N'BIND (FKIP)',                     N'custom', N'inactive', 1, N'fkip'),
    (N'https://bing.fkip.unila.ac.id',                     N'BING (FKIP)',                     N'custom', N'inactive', 1, N'fkip'),
    (N'https://bk.fkip.unila.ac.id',                       N'BK (FKIP)',                       N'custom', N'active',   1, N'fkip'),
    (N'https://borang.fkip.unila.ac.id',                   N'Borang (FKIP)',                   N'custom', N'inactive', 1, N'fkip'),
    (N'https://bujang.fkip.unila.ac.id',                   N'Bujang (FKIP)',                   N'custom', N'inactive', 1, N'fkip'),
    (N'https://cloud.fkip.unila.ac.id',                    N'Cloud (FKIP)',                    N'custom', N'inactive', 1, N'fkip'),
    (N'https://coba.fkip.unila.ac.id',                     N'Coba/Test (FKIP)',                N'custom', N'active',   1, N'fkip'),
    (N'https://cope2019.fkip.unila.ac.id',                 N'COPE 2019 (FKIP)',                N'custom', N'inactive', 1, N'fkip'),
    (N'https://database.fkip.unila.ac.id',                 N'Database (FKIP)',                 N'custom', N'inactive', 1, N'fkip'),
    (N'https://dosen.fkip.unila.ac.id',                    N'Dosen (FKIP)',                    N'custom', N'inactive', 1, N'fkip'),
    (N'https://dpi.fkip.unila.ac.id',                      N'DPI (FKIP)',                      N'custom', N'inactive', 1, N'fkip'),
    (N'https://dpm.fkip.unila.ac.id',                      N'DPM (FKIP)',                      N'custom', N'inactive', 1, N'fkip'),
    (N'https://e-jurnal.fkip.unila.ac.id',                 N'E-Jurnal (FKIP)',                 N'custom', N'inactive', 1, N'fkip'),
    (N'https://ec.fkip.unila.ac.id',                       N'EC (FKIP)',                       N'custom', N'inactive', 1, N'fkip'),
    (N'https://ecic.fkip.unila.ac.id',                     N'ECIC (FKIP)',                     N'custom', N'inactive', 1, N'fkip'),
    (N'https://educloud.fkip.unila.ac.id',                 N'EduCloud (FKIP)',                 N'custom', N'inactive', 1, N'fkip'),
    (N'https://edudata.fkip.unila.ac.id',                  N'EduData (FKIP)',                  N'custom', N'active',   1, N'fkip'),
    (N'https://eduheart.fkip.unila.ac.id',                 N'EduHeart (FKIP)',                 N'custom', N'inactive', 1, N'fkip'),
    (N'https://eduppg.fkip.unila.ac.id',                   N'EduPPG (FKIP)',                   N'custom', N'inactive', 1, N'fkip'),
    (N'https://eduspot.fkip.unila.ac.id',                  N'EduSpot (FKIP)',                  N'custom', N'inactive', 1, N'fkip'),
    (N'https://eduspotnews.fkip.unila.ac.id',              N'EduSpotNews (FKIP)',              N'custom', N'inactive', 1, N'fkip'),
    (N'https://eduspottv.fkip.unila.ac.id',                N'EduSpotTV (FKIP)',                N'custom', N'inactive', 1, N'fkip'),
    (N'https://edutalk.fkip.unila.ac.id',                  N'EduTalk (FKIP)',                  N'custom', N'inactive', 1, N'fkip'),
    (N'https://elearning.fkip.unila.ac.id',                N'E-Learning (FKIP)',               N'custom', N'inactive', 1, N'fkip'),
    (N'https://ekonomi.fkip.unila.ac.id',                  N'Ekonomi (FKIP)',                  N'custom', N'inactive', 1, N'fkip'),
-- === FMIPA (Matematika dan IPA) ===
    (N'https://agenda-pimpinan.fmipa.unila.ac.id',         N'Agenda Pimpinan (FMIPA)',         N'custom', N'inactive', 1, N'fmipa'),
    (N'https://analit.fmipa.unila.ac.id',                  N'Analit (FMIPA)',                  N'custom', N'active',   1, N'fmipa'),
    (N'https://anemon.fmipa.unila.ac.id',                  N'Anemon (FMIPA)',                  N'custom', N'inactive', 1, N'fmipa'),
    (N'https://anemondc.fmipa.unila.ac.id',                N'AnemonDC (FMIPA)',                N'custom', N'inactive', 1, N'fmipa'),
    (N'https://apps.fmipa.unila.ac.id',                    N'Apps (FMIPA)',                    N'custom', N'active',   1, N'fmipa'),
    (N'https://bem.fmipa.unila.ac.id',                     N'BEM (FMIPA)',                     N'custom', N'active',   1, N'fmipa'),
    (N'https://biologi.fmipa.unila.ac.id',                 N'Biologi (FMIPA)',                 N'custom', N'active',   1, N'fmipa'),
    (N'https://conference.fmipa.unila.ac.id',              N'Conference (FMIPA)',              N'custom', N'active',   1, N'fmipa'),
    (N'https://data-kimia.fmipa.unila.ac.id',              N'Data Kimia (FMIPA)',              N'custom', N'active',   1, N'fmipa'),
    (N'https://doktor.fmipa.unila.ac.id',                  N'Doktor (FMIPA)',                  N'custom', N'active',   1, N'fmipa'),
    (N'https://dpm.fmipa.unila.ac.id',                     N'DPM (FMIPA)',                     N'custom', N'active',   1, N'fmipa'),
-- === FH (Hukum) ===
    (N'https://alumni.fh.unila.ac.id',                     N'Alumni (FH)',                     N'custom', N'inactive', 1, N'fh'),
    (N'https://bkbh.fh.unila.ac.id',                       N'BKBH (FH)',                       N'custom', N'inactive', 1, N'fh'),
    (N'https://bem.fh.unila.ac.id',                        N'BEM (FH)',                        N'custom', N'inactive', 1, N'fh'),
    (N'https://cepalo.fh.unila.ac.id',                     N'Cepalo (FH)',                     N'custom', N'inactive', 1, N'fh'),
    (N'https://doktor.fh.unila.ac.id',                     N'Doktor (FH)',                     N'custom', N'active',   1, N'fh'),
    (N'https://dosen.fh.unila.ac.id',                      N'Dosen (FH)',                      N'custom', N'inactive', 1, N'fh'),
    (N'https://ejournal.fh.unila.ac.id',                   N'E-Journal (FH)',                  N'custom', N'active',   1, N'fh'),
-- === FT/ENG (Teknik) ===
    (N'https://analisstruktur.eng.unila.ac.id',            N'Analisis Struktur (FT)',          N'custom', N'inactive', 1, N'eng'),
    (N'https://bem.eng.unila.ac.id',                       N'BEM (FT)',                        N'custom', N'inactive', 1, N'eng'),
    (N'https://bengkelbaja.eng.unila.ac.id',               N'Bengkel Baja (FT)',               N'custom', N'inactive', 1, N'eng'),
    (N'https://buletininsinyur.eng.unila.ac.id',           N'Buletin Insinyur (FT)',           N'custom', N'inactive', 1, N'eng'),
    (N'https://chem.eng.unila.ac.id',                      N'Teknik Kimia (FT)',               N'custom', N'active',   1, N'eng'),
    (N'https://civil.eng.unila.ac.id',                     N'Teknik Sipil (FT)',               N'custom', N'inactive', 1, N'eng'),
    (N'https://cnc.eng.unila.ac.id',                       N'CNC (FT)',                        N'custom', N'inactive', 1, N'eng'),
    (N'https://comon.eng.unila.ac.id',                     N'COMON (FT)',                      N'custom', N'inactive', 1, N'eng'),
    (N'https://dies.eng.unila.ac.id',                      N'Dies (FT)',                       N'custom', N'inactive', 1, N'eng'),
    (N'https://dosen.eng.unila.ac.id',                     N'Dosen (FT)',                      N'custom', N'inactive', 1, N'eng'),
    (N'https://elektro.eng.unila.ac.id',                   N'Elektro (FT)',                    N'custom', N'active',   1, N'eng'),
    (N'https://elektronika.eng.unila.ac.id',               N'Elektronika (FT)',                N'custom', N'active',   1, N'eng'),
    (N'https://ee.unila.ac.id',                            N'Teknik Elektro (EE)',             N'custom', N'inactive', 1, N'eng'),
    (N'https://akreditasi.ee.unila.ac.id',                 N'Akreditasi (EE)',                 N'custom', N'inactive', 1, N'eng'),
    (N'https://alumni.ee.unila.ac.id',                     N'Alumni (EE)',                     N'custom', N'inactive', 1, N'eng'),
    (N'https://digilib.ee.unila.ac.id',                    N'Digilib (EE)',                    N'custom', N'inactive', 1, N'eng'),
    (N'https://akreditasi.if.unila.ac.id',                 N'Akreditasi IF',                   N'custom', N'inactive', 1, N'eng'),
-- === LPPM ===
    (N'https://business-incubators.lppm.unila.ac.id',      N'Business Incubators (LPPM)',      N'custom', N'inactive', 1, N'lppm'),
    (N'https://conference.lppm.unila.ac.id',               N'Conference (LPPM)',               N'custom', N'active',   1, N'lppm'),
-- === Pascasarjana ===
    (N'https://dil.pasca.unila.ac.id',                     N'DIL Pascasarjana',               N'custom', N'active',   1, N'pasca'),
-- === Ilkom ===
    (N'https://alumni.ilkom.unila.ac.id',                  N'Alumni (Ilkom)',                  N'custom', N'inactive', 1, N'ilkom'),
    (N'https://app.ilkom.unila.ac.id',                     N'App (Ilkom)',                     N'custom', N'inactive', 1, N'ilkom'),
    (N'https://apps.ilkom.unila.ac.id',                    N'Apps (Ilkom)',                    N'custom', N'inactive', 1, N'ilkom'),
-- === PUI ===
    (N'https://biodiversity.pui.unila.ac.id',              N'Biodiversity (PUI)',              N'custom', N'active',   1, N'pui'),
-- === CCED ===
    (N'https://ac-cced.unila.ac.id',                       N'AC-CCED',                        N'custom', N'active',   1, N'cced'),
    (N'https://begawi.cced.unila.ac.id',                   N'Begawi (CCED)',                   N'custom', N'inactive', 1, N'cced'),
    (N'https://belajar.cced.unila.ac.id',                  N'Belajar (CCED)',                  N'custom', N'inactive', 1, N'cced'),
    (N'https://cced.unila.ac.id',                          N'CCED Unila',                      N'custom', N'active',   1, N'cced'),
-- === SDG Center ===
    (N'https://dashboard.sdgcenter.unila.ac.id',           N'Dashboard SDG Center',           N'custom', N'active',   1, N'sdgcenter'),
-- === HETI ===
    (N'https://cd.heti.unila.ac.id',                       N'CD HETI',                        N'custom', N'active',   1, N'heti'),
-- === TIK / PUSKOM ===
    (N'https://adpc15.puskom.unila.ac.id',                 N'ADPC15 (PUSKOM)',                 N'custom', N'inactive', 1, N'tik'),
    (N'https://arsip.tik.unila.ac.id',                     N'Arsip (TIK)',                     N'custom', N'inactive', 1, N'tik'),
    (N'https://aset-tik.unila.ac.id',                      N'Aset TIK',                       N'custom', N'inactive', 1, N'tik'),
    (N'https://cctv.ltsit.unila.ac.id',                    N'CCTV LTSIT',                     N'custom', N'inactive', 1, N'tik'),
    (N'https://cctv.tik.unila.ac.id',                      N'CCTV TIK',                       N'custom', N'inactive', 1, N'tik'),
-- === BPPMB ===
    (N'https://bppmb.unila.ac.id',                         N'BPPMB Unila',                    N'custom', N'inactive', 1, N'bppmb'),
    (N'https://e-kendali.bppmb.unila.ac.id',               N'E-Kendali (BPPMB)',              N'custom', N'inactive', 1, N'bppmb'),
-- === BKSB ===
    (N'https://ejportal.bksb.unila.ac.id',                 N'EJPortal (BKSB)',                N'custom', N'inactive', 1, N'bksb'),
-- === Institutional (Unila-level) ===
    (N'https://Pendamas.unila.ac.id',                      N'Pendamas Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://admisi.unila.ac.id',                        N'Admisi Unila',                   N'custom', N'active',   1, NULL),
    (N'https://aduankonten.unila.ac.id',                   N'Aduan Konten Unila',             N'custom', N'active',   1, NULL),
    (N'https://ae.unila.ac.id',                            N'AE Unila',                       N'custom', N'inactive', 1, NULL),
    (N'https://agenda.unila.ac.id',                        N'Agenda Unila',                   N'custom', N'active',   1, NULL),
    (N'https://agenda2.unila.ac.id',                       N'Agenda 2 Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://agrotropika.unila.ac.id',                   N'Agrotropika Unila',              N'custom', N'inactive', 1, NULL),
    (N'https://aipt.unila.ac.id',                          N'AIPT Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://akreditasi.unila.ac.id',                    N'Akreditasi Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://akses.unila.ac.id',                         N'Akses Unila',                    N'custom', N'active',   1, NULL),
    (N'https://altronila.unila.ac.id',                     N'Altronila',                      N'custom', N'inactive', 1, NULL),
    (N'https://alwasii.unila.ac.id',                       N'Alwasii Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://angka.unila.ac.id',                         N'Angka Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://anjab.unila.ac.id',                         N'Anjab Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://anjungan.unila.ac.id',                      N'Anjungan Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://apps.unila.ac.id',                          N'Apps Unila',                     N'custom', N'active',   1, NULL),
    (N'https://ars.unila.ac.id',                           N'ARS Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://arsip.unila.ac.id',                         N'Arsip Unila',                    N'custom', N'active',   1, NULL),
    (N'https://aruba.unila.ac.id',                         N'Aruba Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://assesment.unila.ac.id',                     N'Assessment Unila',               N'custom', N'active',   1, NULL),
    (N'https://audit-dc.unila.ac.id',                      N'Audit DC Unila',                 N'custom', N'active',   1, NULL),
    (N'https://audit-dc1.unila.ac.id',                     N'Audit DC1 Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://baak.unila.ac.id',                          N'BAAK Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://backupvclass.unila.ac.id',                  N'Backup VClass Unila',            N'custom', N'inactive', 1, NULL),
    (N'https://baitul-ummah.unila.ac.id',                  N'Baitul Ummah Unila',             N'custom', N'inactive', 1, NULL),
    (N'https://bak.unila.ac.id',                           N'BAK Unila',                      N'custom', N'active',   1, NULL),
    (N'https://bauk.unila.ac.id',                          N'BAUK Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://beasiswa.unila.ac.id',                      N'Beasiswa Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://belajar.unila.ac.id',                       N'Belajar Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://bem-u.unila.ac.id',                         N'BEM-U Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://bem.unila.ac.id',                           N'BEM Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://bgbd.unila.ac.id',                          N'BGBD Unila',                     N'custom', N'active',   1, NULL),
    (N'https://bimasakti.unila.ac.id',                     N'Bimasakti Unila',                N'custom', N'active',   1, NULL),
    (N'https://biomass.unila.ac.id',                       N'Biomass Unila',                  N'custom', N'active',   1, NULL),
    (N'https://bios.unila.ac.id',                          N'BIOS Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://birohmah.unila.ac.id',                      N'Birohmah Unila',                 N'custom', N'active',   1, NULL),
    (N'https://bkd.sister.unila.ac.id',                    N'BKD Sister Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://bkd.unila.ac.id',                           N'BKD Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://bpa.unila.ac.id',                           N'BPA Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://bpalku.unila.ac.id',                        N'BPALKU Unila',                   N'custom', N'inactive', 1, NULL),
    (N'https://bphm.unila.ac.id',                          N'BPHM Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://bpig.unila.ac.id',                          N'BPIG Unila',                     N'custom', N'active',   1, NULL),
    (N'https://bpinfra.unila.ac.id',                       N'BPINFRA Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://bpkhm.unila.ac.id',                         N'BPKHM Unila',                    N'custom', N'active',   1, NULL),
    (N'https://bpmku.unila.ac.id',                         N'BPMKU Unila',                    N'custom', N'active',   1, NULL),
    (N'https://bpu.unila.ac.id',                           N'BPU Unila',                      N'custom', N'active',   1, NULL),
    (N'https://br.unila.ac.id',                            N'BR Unila',                       N'custom', N'active',   1, NULL),
    (N'https://bse.unila.ac.id',                           N'BSE Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://buk.unila.ac.id',                           N'BUK Unila',                      N'custom', N'active',   1, NULL),
    (N'https://bumidatar.unila.ac.id',                     N'Bumidatar Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://bus.unila.ac.id',                           N'BUS Unila',                      N'custom', N'active',   1, NULL),
    (N'https://cache.unila.ac.id',                         N'Cache Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://cachebone.unila.ac.id',                     N'Cachebone Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://cacti.unila.ac.id',                         N'Cacti Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://cas.unila.ac.id',                           N'CAS Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://catd3.unila.ac.id',                         N'CAT D3 Unila',                   N'custom', N'active',   1, NULL),
    (N'https://cctv.unila.ac.id',                          N'CCTV Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://cctvbmn.unila.ac.id',                       N'CCTV BMN Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://chat.unila.ac.id',                          N'Chat Unila',                     N'custom', N'active',   1, NULL),
    (N'https://cigre.unila.ac.id',                         N'CIGRE Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://clone.unila.ac.id',                         N'Clone Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://cloud.unila.ac.id',                         N'Cloud Unila',                    N'custom', N'active',   1, NULL),
    (N'https://cluster.unila.ac.id',                       N'Cluster Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://clusterdb.unila.ac.id',                     N'Cluster DB Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://comon.unila.ac.id',                         N'COMON Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://conference.unila.ac.id',                    N'Conference Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://covid19.unila.ac.id',                       N'COVID-19 Unila',                 N'custom', N'inactive', 1, NULL),
    (N'https://cpl.unila.ac.id',                           N'CPL Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://csirt.unila.ac.id',                         N'CSIRT Unila',                    N'custom', N'active',   1, NULL),
    (N'https://ct.unila.ac.id',                            N'CT Unila',                       N'custom', N'inactive', 1, NULL),
    (N'https://d3-fe.unila.ac.id',                         N'D3 FE Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://dapelmikpdpt.unila.ac.id',                  N'Dapelmik PDPT Unila',            N'custom', N'active',   1, NULL),
    (N'https://daring.unila.ac.id',                        N'Daring Unila',                   N'custom', N'inactive', 1, NULL),
    (N'https://dashboard-buk.unila.ac.id',                 N'Dashboard BUK Unila',            N'custom', N'active',   1, NULL),
    (N'https://dashboard-kampusmerdeka.unila.ac.id',       N'Dashboard Kampus Merdeka',       N'custom', N'active',   1, NULL),
    (N'https://dashboard.buk.unila.ac.id',                 N'Dashboard BUK 2 Unila',          N'custom', N'active',   1, NULL),
    (N'https://dashboard.unila.ac.id',                     N'Dashboard Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://data.unila.ac.id',                          N'Data Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://data.aipt.unila.ac.id',                     N'Data AIPT Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://dataku.unila.ac.id',                        N'DataKu Unila',                   N'custom', N'inactive', 1, NULL),
    (N'https://demo.unila.ac.id',                          N'Demo Unila',                     N'custom', N'inactive', 1, NULL),
    (N'https://dev-agenda.unila.ac.id',                    N'Dev Agenda Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://dev-inf.unila.ac.id',                       N'Dev INF Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://dev-web.unila.ac.id',                       N'Dev Web Unila',                  N'custom', N'active',   1, NULL),
    (N'https://dies.unila.ac.id',                          N'Dies Natalis Unila',             N'custom', N'inactive', 1, NULL),
    (N'https://diesnatalis.unila.ac.id',                   N'Dies Natalis Unila 2',           N'custom', N'inactive', 1, NULL),
    (N'https://digilib.unila.ac.id',                       N'Digilib Unila',                  N'custom', N'active',   1, NULL),
    (N'https://digilib2.unila.ac.id',                      N'Digilib 2 Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://digitalplan.unila.ac.id',                   N'Digital Plan Unila',             N'custom', N'inactive', 1, NULL),
    (N'https://direktori.unila.ac.id',                     N'Direktori Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://doktor.unila.ac.id',                        N'Program Doktor Unila',           N'custom', N'active',   1, NULL),
    (N'https://dosen.unila.ac.id',                         N'Dosen Unila',                    N'custom', N'inactive', 1, NULL),
    (N'https://dpm.unila.ac.id',                           N'DPM Unila',                      N'custom', N'active',   1, NULL),
    (N'https://dpm.u.kbm.unila.ac.id',                    N'DPM KBM Unila',                  N'custom', N'inactive', 1, NULL),
    (N'https://dss.unila.ac.id',                           N'DSS Unila',                      N'custom', N'inactive', 1, NULL),
    (N'https://dummy.siakadu.unila.ac.id',                 N'Dummy SIAKADU',                  N'custom', N'inactive', 1, NULL),
    (N'https://dummyisip.unila.ac.id',                     N'Dummy ISIP Unila',               N'custom', N'active',   1, NULL),
    (N'https://dwp.unila.ac.id',                           N'DWP Unila',                      N'custom', N'active',   1, NULL),
    (N'https://e-commerce.unila.ac.id',                    N'E-Commerce Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://e-kkn.unila.ac.id',                         N'E-KKN Unila',                    N'custom', N'active',   1, NULL),
    (N'https://e-learning.unila.ac.id',                    N'E-Learning Unila',               N'custom', N'inactive', 1, NULL),
    (N'https://e-lp3m.unila.ac.id',                        N'E-LP3M Unila',                   N'custom', N'inactive', 1, NULL),
    (N'https://e-proceeding.unila.ac.id',                  N'E-Proceeding Unila',             N'custom', N'inactive', 1, NULL),
    (N'https://e-reservasi.unila.ac.id',                   N'E-Reservasi Unila',              N'custom', N'inactive', 1, NULL),
    (N'https://eabsensi.ujicoba.unila.ac.id',              N'E-Absensi Ujicoba',              N'custom', N'inactive', 1, NULL),
    (N'https://ejournal.unila.ac.id',                      N'E-Journal Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://ejurnal.unila.ac.id',                       N'E-Jurnal Unila',                 N'custom', N'active',   1, NULL),
    (N'https://ekinerja.ujicoba.unila.ac.id',              N'E-Kinerja Ujicoba',              N'custom', N'inactive', 1, NULL),
    (N'https://electrician.unila.ac.id',                   N'Electrician Unila',              N'custom', N'active',   1, NULL),
    (N'https://elementor.unila.ac.id',                     N'Elementor Unila',                N'custom', N'inactive', 1, NULL),
    (N'https://email.unila.ac.id',                         N'Email Unila',                    N'custom', N'active',   1, NULL)
) AS S(url, name, platform, status, is_active, fakultas_id)
ON T.url = S.url AND T.soft_delete = 0
WHEN NOT MATCHED THEN
    INSERT (id, url, name, platform, status, is_active, fakultas_id, create_date, id_creator, last_update, soft_delete)
    VALUES (NEWID(), S.url, S.name, S.platform, S.status, S.is_active, S.fakultas_id,
            GETDATE(), '00000000-0000-0000-0000-000000000001', GETDATE(), 0);
GO

-- Verifikasi
SELECT COUNT(*) AS total_sites FROM monitoring.sites WHERE soft_delete = 0
GO
SELECT status, COUNT(*) AS jumlah FROM monitoring.sites WHERE soft_delete = 0 GROUP BY status
GO
SELECT fakultas_id, COUNT(*) AS jumlah FROM monitoring.sites WHERE soft_delete = 0 GROUP BY fakultas_id ORDER BY jumlah DESC
GO
