-- ============================================================
-- monitoring_15_seed_keywords_gsc.sql
-- Seed data: keyword judol dari Google Search Console
-- Source: electrician.unila.ac.id GSC export 2026-03-05
-- Total ~1004 query CSV, ~950 query judi, sisanya akademik
-- Melengkapi monitoring_14 (generic) dengan brand + varian typo
-- ============================================================

declare @system_user uniqueidentifier = '00000000-0000-0000-0000-000000000001'
declare @now datetime = getdate()

-- Hapus data GSC sebelumnya (idempoten)
delete from monitoring.threat_keywords
where id_creator = @system_user
  and notes = 'gsc-electrician-2026'
go

-- ============================================================
-- BATCH 1: olxtoto utama + varian klik tinggi (>100 klik)
-- ============================================================
declare @system_user uniqueidentifier = '00000000-0000-0000-0000-000000000001'
declare @now datetime = getdate()

insert into monitoring.threat_keywords
    (keyword, category, weight, is_active, notes, create_date, id_creator, last_update, soft_delete)
values
-- Weight 10: >10K klik
('olxtoto',                'brand_judol', 10, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto modal spin maxwin','brand_judol',10, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login masuk',    'brand_judol', 10, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto',               'brand_judol', 10, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login',          'brand_judol', 10, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- Weight 9: 1K-10K klik
('olxtoto login olx no1',  'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxltoto',                'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotototo',            'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macau',          'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --link',         'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel',          'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olktoto',                'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot',           'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olextoto',               'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --login',        'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto heylink link alternatif login','brand_judol',9,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto 288 login link alternatif','brand_judol',9,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto bet 100 login',  'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login togel',    'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --togel',        'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel terpercaya','brand_judol', 9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto macau 4d',      'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --slot',         'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login togel login','brand_judol',9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login masuk login','brand_judol',9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoro',                'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --macau',        'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --daftar',       'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login olxtoto',  'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot login',     'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link',           'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto heylink link alternatif','brand_judol',9,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto login slot online','brand_judol',9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link asli',      'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.',               'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto asli',           'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login togel gacor','brand_judol',9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto top',            'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('www olxtoto com online', 'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtot',                 'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login slot',     'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --olxtoto',      'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto jitu togel',     'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 88 slot',        'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login olxtoto togel',    'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link olxtoto',           'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel login',    'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto macau',         'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link alternatif','brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oloxtoto',               'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 4d',             'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olk toto',               'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto togel',         'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alxtoto',                'brand_judol',  9, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtito',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link slot gacor login','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('oltoto',                 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link alternatife olxtoto login','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoti',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto. suka login',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxtoto',                 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxl toto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto macau login',   'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macau login',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto olxtoto',        'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtototo',              'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link olx togel login',   'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxroto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot online',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login olxtoto slot login','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto toto',           'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto macau 4d login','brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto gacor',          'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto login',         'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto rtp',            'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs olxtoto',          'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- situs',       'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxoto',                 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('0lxtoto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olex toto',              'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto resmi',          'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olctoto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login slot rtp', 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togel olxtoto',          'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto asia',           'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs olx toto',         'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto terbaru',        'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxyoto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto resmi login',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotot',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto bet 100 link alternatif','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olx totto',              'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto togel login',   'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotototo togel',      'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.com',            'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot gacor login','brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 88',             'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto menang gacor',   'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('okxtoto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login link',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login asli',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxttoto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login resmi',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- link',        'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx tato',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto @bandar togel',  'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olektoto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login alternatif','brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoo',                 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('opxtoto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxototo',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot resmi',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx.toto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- login',       'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macau resmi',    'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login togel alternatif login','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('slot olxtoto',           'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto kasih',          'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto terpercaya',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto no 1',           'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macau login link alternatif','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoyo',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alextoto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto bet 100',        'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxroro',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto modal spin maxwin login','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto alternatif',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs slot olxtoto',     'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ollxtoto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxloto',                'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 88 login',       'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar togel terpercaya olxtoto','brand_judol',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto the best gaming','brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto web login',      'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxstoto',               'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 100',            'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login web',      'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtto',                 'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0)
go

-- ============================================================
-- BATCH 2: olxtoto varian klik sedang (10-99 klik)
-- ============================================================
declare @system_user uniqueidentifier = '00000000-0000-0000-0000-000000000001'
declare @now datetime = getdate()

insert into monitoring.threat_keywords
    (keyword, category, weight, is_active, notes, create_date, id_creator, last_update, soft_delete)
values
('olxtoto login no. 1',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto bandar online terpercaya','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto login link alternatif','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olixtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto @situs toto',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login masuk akun','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto @slot online',   'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('extoto',                 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto resmi',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoot',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olztoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oldtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ooxtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtpto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ilxtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --situs',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('satu olxtoto',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto toto macau',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto slot',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto draw',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto vip',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotp',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotoo',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxloto',                 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macau 4d',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toro',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login olxtoto',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- togel',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link slot gacor','brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('live olxtoto',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx tot',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxlototo',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.io',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link login',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto baru',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto alternative',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oolxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxotto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtooto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot online terpercaya','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('alexitoto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 2026',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto vip login',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto resmi dan terpercaya','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto link resmi login','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot rtp',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link resmi olxtoto',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto jitu login',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto 4d',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto ling',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto daftar',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel terpercaya login','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto 4d 2025',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- daftar',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link resmi',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('obltoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto alternatif resmi','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('aplikasi resmi olxtoto', 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto macao',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxotot',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxktoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot olxtoto 26',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto hidup',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('macau olxtoto',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('rtp slot olxtoto',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('masuk olxtoto macau',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link slot gacor olxtoto','brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto paling gacor',   'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ulxtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxs toto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto 88',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto jitu',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs olxtoto asli',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toti',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oelextoto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oletoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('exltoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olkstoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto suka login',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto xd',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxlotto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto --alternatif',   'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto maxwin',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 25',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('klxtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olototo',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oelxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto us',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 138',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto99 login',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.id',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto apk login',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto online',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto situs togel',   'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel login alternatif','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olstoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtt',                  'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto.',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olvtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto gacor hari ini', 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto alternatif login','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto masuk',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto link alternatif bandar toto resmi paling aman','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olx toto asli',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link alternatif olxtoto','brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs togel olxtoto',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 1',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtor',                 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ol toto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alx toto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtorto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtato',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtog',                 'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ols toto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 26',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oixtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ol xtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login no 1',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oleks toto',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('rolxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oxltoto togel',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login asia',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotolink',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot gacor',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto situs resmi',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto rtp slot',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link alternatif olx toto','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login olx slot toto',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx totot',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olltoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('oke woles togel login',  'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ollx toto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('aloxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto situs toto',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtotototo login',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot login link alternatif','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto asli login',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto eu.com',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.slot',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto. login',         'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('apk olxtoto',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto asia login alternatif','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('.olxtoto',               'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar togel terpercaya olxtoto login','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto macau olxtoto slot','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('xl toto login',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto terbaru',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link asli olxtoto',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto slot link alternatif','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('olxtoto togel slot macau','brand_judol', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.login',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alek toto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto -- slot',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olox toto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto situs slot',     'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto akun demo',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto io',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto o',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situsolxtoto',           'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx toto alternatif',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link olxtoto alternatif','brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login link alternatif terbaru','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('situs oxltoto',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto login rtp',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto minimal deposit','brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto official',       'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs resmi olxtoto',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 176',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('xl toto togel',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto mahjong',        'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 88win',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('paito olxtoto',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto79win.online --win','brand_judol',7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olekstoto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto jamin',          'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto 24',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto togel resmi',    'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto no1',            'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto alternatif olxtoto login macau','brand_judol',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('link slot olxtoto',      'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto eu',             'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0)
go

-- ============================================================
-- BATCH 3: brand lain (non-olxtoto) + idrhoki138 patterns
-- ============================================================
declare @system_user uniqueidentifier = '00000000-0000-0000-0000-000000000001'
declare @now datetime = getdate()

insert into monitoring.threat_keywords
    (keyword, category, weight, is_active, notes, create_date, id_creator, last_update, soft_delete)
values
-- idrhoki138 + gacorin (3500+ tayangan per query)
('agen gacorin 2--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link gacorin 1--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('depo gacorin 1--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link gacorin 2--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('depo gacorin 2--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('agen gacorin 1--idrhoki138.com',  'brand_judol', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot gacorin 1--idrhoki138.it.com','brand_judol',7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togelmacau --4d(idrhoki138.it.com)','brand_judol',7,1,'gsc-electrician-2026', @now, @system_user, @now, 0),
('idrhoki138',             'brand_judol',  8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('gacorin',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- mawartoto
('mawartoto',              'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawartoto slot resmi',   'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawartoto 4d',           'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawar togel',            'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawar togel 808.online-win','brand_judol',6,1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawar toto 4d',          'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawartoto link gacor',   'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mawartoto 4d login',     'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- nixtoto (6K tayangan)
('nixtoto',                'brand_judol',  7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- bukagaming
('bukagaming',             'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link toto macau bukagaming','brand_judol',6,1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link togel macau bukagaming','brand_judol',5,1,'gsc-electrician-2026', @now, @system_user, @now, 0),

-- luna togel
('luna togel',             'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('luna togel link alternatif 176','brand_judol',6,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('luna togel 176',         'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- togel777
('togel777',               'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togel777 login',         'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('star togel777',          'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar togel777',        'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ling togel777',          'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- alexistoto / alexatoto
('alexistoto',             'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alexatoto',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alexistoto79.online --vip','brand_judol',5,1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alexitoto',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- brand kecil lainnya
('nobitabet',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('nobitabet login',        'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('fixplay666',             'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('fixplay666 login',       'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('tanggo77',               'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('tanggo77 login',         'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('tempetoto',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('unitoto',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('plntoto',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('altogel',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link altogel slot777',   'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('mataslot77',             'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('josbet',                 'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bola slot ++josbet',     'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('coloksgp',               'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('sambal toto',            'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('rolextoto',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('luxtoto',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('poltoto',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('suka toto',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('ahlitoto',               'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('dlbtoto',                'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('best togel',             'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('best togel login link alternatif','brand_judol',5,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('best togel link login',  'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot777resmi',           'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('wd yuk 168 login',       'brand_judol',  4, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('indo cair togel',        'brand_judol',  4, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('cair 50 link alternatif','brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto188.vip',         'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto79win.online',    'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot demo aztec bonanza','brand_judol',  4, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('demo slot aztec bonanza','brand_judol',  4, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('goltoto',                'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alxistoto',              'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olexstoto',              'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('alektoto',               'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olextot',                'brand_judol',  6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('old togel',              'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('daftar olxtoto',         'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('download olxtoto',       'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.co',             'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('www.olxtoto',            'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('www.olxtoto.com',        'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olxtoto.net',            'brand_judol',  5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0)
go

-- ============================================================
-- BATCH 4: situs_toto + pattern_hack
-- ============================================================
declare @system_user uniqueidentifier = '00000000-0000-0000-0000-000000000001'
declare @now datetime = getdate()

insert into monitoring.threat_keywords
    (keyword, category, weight, is_active, notes, create_date, id_creator, last_update, soft_delete)
values
-- situs_toto
('situs toto',             'situs_toto',   8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs toto online',      'situs_toto',   8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs toto online terbaik','situs_toto', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('toto macau',             'situs_toto',   8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('toto macau 4d',          'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar toto',            'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('toto online',            'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs toto macau',       'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('toto asia login',        'situs_toto',   6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togel online asia',      'situs_toto',   6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('tototerpercaya',         'situs_toto',   6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togelmacau',             'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs togel',            'situs_toto',   7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),

-- pattern_hack
('login masuk',            'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('modal spin maxwin',      'pattern_hack', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('heylink link alternatif','pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('heylink link alternatif login','pattern_hack',7,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('bet 100',                'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bet 100 login',          'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link slot gacor login',  'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('pasaran terlengkap',     'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('agen judi slot online',  'pattern_hack', 8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar togel online terpercaya','pattern_hack',8,1,'gsc-electrician-2026',@now,@system_user,@now,0),
('bocoran rtp slot tergacor','pattern_hack',8, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('288 login link alternatif','pattern_hack',7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login togel gacor',      'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot gacor login',       'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs slot terpercaya',  'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar togel terpercaya','pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link alternatif login',  'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot online terpercaya', 'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togel terpercaya',       'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs togel online',     'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login togel login',      'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login masuk login',      'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('login masuk akun',       'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('link alternatif terbaru','pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot resmi login',       'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('menang gacor',           'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('paling gacor',           'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('bandar online terpercaya','pattern_hack',7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot login link alternatif','pattern_hack',6,1,'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs slot',             'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('togel slot macau',       'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot gacor olxtoto',     'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('demo slot',              'pattern_hack', 5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('slot demo',              'pattern_hack', 5, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('game slot',              'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('selot',                  'pattern_hack', 6, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx togel slot',         'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx togel link',         'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('situs olx togel',        'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0),
('olx situs toto',         'pattern_hack', 7, 1, 'gsc-electrician-2026', @now, @system_user, @now, 0)
go

-- ============================================================
-- Verifikasi
-- ============================================================
select category, count(*) as total, avg(weight) as avg_weight
from monitoring.threat_keywords
where notes = 'gsc-electrician-2026'
group by category
order by category
go

select count(*) as grand_total
from monitoring.threat_keywords
where notes = 'gsc-electrician-2026'
go

print 'Seed data GSC threat_keywords inserted.'
go
